# Generated by Django 4.2.14 on 2024-07-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatmeninas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMeninas',
            new_name='SalaMeninas',
        ),
    ]
