# Generated by Django 4.2.14 on 2024-07-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chatmeninas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMeninas',
        ),
    ]
