# Generated by Django 4.2.14 on 2024-07-29 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0005_delete_chatmeninas'),
    ]

    operations = [
        migrations.AddField(
            model_name='salameninas',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
